jwt:
  secret: ${JWT_SECRET}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: warn
    com.basic.backend: info

app:
  cors:
    allowed-origins:
      - https://service.example.com

swagger:
  enabled: false